import { Cairo } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const cairo = Cairo({ subsets: ["latin"] });

export const metadata = {
  title: "Log in Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main className={`${cairo.className} bg-[#E9E9E9]`}>
      {children}
      <ToastContainer />
    </main>
  );
}
